### ISSUE TITLE
Leveraging Stereo-Camera Data for Real-Time Dynamic Obstacle Detection and Tracking

### ISSUE THREAD

**Issue by CTGUMARK** [sevensense-robotics/alphasense_core_manual#12]
I am an undergraduate student and I can't implement it myself after reading the thesis  about Leveraging Stereo-Camera Data for Real-Time Dynamic Obstacle Detection and Tracking, so I would like to ask, is the code of this program open source?

**Comment by Eeppii** [comment]
@CTGUMARK thanks a lot for your interest in our paper. Unfortunately, there won't be any code opensourced as the work is proprietary to Sevensense Robotics.

**Comment by DasUniversum** [comment]
I have read the paper Leveraging Stereo-Camera Data for Real-Time Dynamic Obstacle Detection and Tracking and I am very interested in it. But I have a question about it, which is how to calculate the velocity of each point in the point cloud, in order to classify objects as static ones or dynamic ones.
